spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ambulante
    password: ambulante
    username: ambulante
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  jpa:
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
  cache:
    cache-names: articleSuggestion
    caffeine.spec: maximumSize=1000,expireAfterWrite=60s
  
